---

- name: assert that required variables are defined
  assert:
    that:
      - ssl_provider is defined
      - ssl_provider in ['selfsigned', 'copy', 'certbot']

- name: install packages required for interacting with OpenSSL
  apt:
    name: python3-cryptography
    state: present

- import_tasks: selfsigned.yml
  when: ssl_provider == 'selfsigned'

- import_tasks: copy.yml
  when: ssl_provider == 'copy'

- import_tasks: certbot.yml
  when: ssl_provider == 'certbot'
