---

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Having an active 'postgresql' module stream for the default CentOS 8 versions
# can prevent dnf/yum from finding our desired postgresql packages.
- name: disable the AppStream postgresql module
  become: yes
  command:
    cmd: dnf module disable postgresql -y
    warn: no

- import_role:
    name: geerlingguy.postgresql
  vars:
    postgresql_version: "13"
    postgresql_enablerepo: pgdg13
    postgresql_packages:
      - postgresql13
      - postgresql13-server
      - postgresql13-contrib
      - postgresql13-libs
    postgresql_data_dir: /var/lib/pgsql/13/data
    postgresql_bin_path: /usr/pgsql-13/bin/
    postgresql_config_path: /var/lib/pgsql/13/data
    postgresql_daemon: postgresql-13
    postgresql_python_library: python3-psycopg2
