---
{% raw %}
- name: ensure firewalld is installed
  yum:
    name: firewalld
    state: present

- name: start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true

- include_tasks: add_zone.yml
  loop: "{{ firewalld_zones }}"
  loop_control:
    loop_var: firewalld_zone

- name: apply firewalld rules
  ansible.posix.firewalld:
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    immediate: true
    permanent: true
    state: "{{ item.state }}"
    zone: "{{ item.zone | default(omit) }}"
  when: item.when | bool
  loop: "{{ firewalld_rules }}"
{% endraw %}
